FROM ros:humble

# Install ROS build tools and Python deps
RUN apt update && \
    apt install -y \
    python3-colcon-common-extensions \
    python3-pip && \
    rm -rf /var/lib/apt/lists/*


# Entry point to launch the node
COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
